# -*- mode: ruby -*-
# vi: set ft=ruby :

OS = "centos/8"

Vagrant.configure("2") do |config|

	config.vm.box = OS

	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
	end
    
	config.vm.define "lchancriS" do |master|
		master.vm.hostname = "lchancriS"
		master.vm.network :private_network, ip: "192.168.42.110"
		master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
		master.vm.provision "shell", privileged: true, path: "scripts/master_node_setup.sh", args: ["192.168.42.110"]
		master.vm.provider "virtualbox" do |v|
			v.name = "lchancriS"
		end
	end
end