# -*- mode: ruby -*-
# vi: set ft=ruby :

OS = "centos/7"

Vagrant.configure("2") do |config|

	config.vm.box = OS

	config.vm.provider "virtualbox" do |v|
		v.memory = 512
		v.cpus = 1
	end
    
	config.vm.define "lchancriS" do |master|
		master.vm.hostname = "lchancriS"
		master.vm.network :private_network, ip: "192.168.56.110"
		master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
		master.vm.provision "shell", privileged: true, path: "script/server.sh", args: ["192.168.56.110"]
		master.vm.provider "virtualbox" do |v|
			v.name = "lchancriS"
		end
	end
end