# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/stream8"

  config.vm.provision "shell", inline: <<-SHELL
    yum install -y net-tools
  SHELL

  config.vm.define "lchancriS"
  config.vm.hostname = "lchancriS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.provision "file", source: "confs/deployment.yaml", destination: "/tmp/deployment.yaml"
  config.vm.provision "file", source: "confs/app1", destination: "/tmp/app1"
  config.vm.provision "file", source: "confs/app2", destination: "/tmp/app2"
  config.vm.provision "file", source: "confs/app3", destination: "/tmp/app3"
  config.vm.provider "virtualbox" do |v|
    v.name = "lchancriS"
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.provision "shell", privileged: true, path: "scripts/install.sh"

end
